services:
  web-creeper:
    build: .
    container_name: web-creeper
    ports:
      - "8000:8000"
    environment:
      MAIN: creeper
      DATABASE_URL: "mysql+asyncmy://${DB_USER:-root}:${DB_PASSWORD:-example}@mariadb:3306/${DB_NAME:-app_db}"
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-example}
      MYSQL_DATABASE: ${DB_NAME:-app_db}
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-pexample", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  mariadb_data:
